"""
Metadata scrub — the "Clean" stage.

Quirky's detector already spots generator metadata leaks: `compute_text_prompt_leak_score`
and the inline PNG-info check in `DetectorEngine._analyze_image` both flag telltale keys
like "parameters", "prompt", "steps", "sampler" -- but nothing acts on what they find. This
module is the other half: report every embedded field in plain language, and strip it via
a clean re-encode.

Why a re-encode is a complete strip, not a best-effort one:
  * PNG: Pillow only writes tEXt/zTXt/iTXt chunks when you explicitly pass `pnginfo=`.
    A plain re-open + re-save with no `pnginfo` kwarg drops every existing text chunk.
  * JPEG/WEBP/TIFF: Pillow only writes EXIF when you explicitly pass `exif=`. A plain
    re-save with no `exif` kwarg drops all EXIF (GPS, camera make/model, generator
    software tags, thumbnails -- all of it).
Both are the standard, well-documented way to strip metadata with Pillow; this module
just makes the behavior explicit, verifiable, and reported back to the caller.

No cryptographic signing here (C2PA is a separate, deliberate decision -- see
docs/QUIRKY_LAYERS_BLUEPRINT.md section 4). The only optional addition is a single
honest, visible attribution tag ("Powered by Quirky (MITPO)") instead of leaving the
file silently blank -- transparency instead of just erasure.
"""
from __future__ import annotations

import os
from typing import Any, Dict, List

from PIL import Image

ATTRIBUTION = "Powered by Quirky (MITPO)"

# Keys that commonly carry AI-generator fingerprints across tools (Automatic1111,
# ComfyUI, InvokeAI, Midjourney exports, etc). A superset of the check in
# detector/formulas.py's compute_text_prompt_leak_score, so Clean can disclose more
# than the passive detector flags while staying consistent with it.
LEAK_KEYS = [
    "parameters", "prompt", "negative prompt", "negative_prompt", "steps", "sampler",
    "sampler_name", "cfg", "cfg_scale", "guidance", "seed", "model", "model_hash",
    "workflow", "generation_data", "comfyui", "generation info",
]

# Codec-structural fields Pillow surfaces via img.info that are NOT metadata anyone
# embedded -- they're regenerated by the encoder on every save (pixel density units,
# JFIF version, interlacing) and carry no generator/creator/personal information.
# Excluded from "should this be stripped" accounting so `fully_clean` doesn't cry wolf
# over fields that are inherent to being a valid JPEG/PNG and can't meaningfully be
# "removed" without corrupting the container format.
STRUCTURAL_KEYS = {
    "jfif", "jfif_version", "jfif_unit", "jfif_density", "dpi", "aspect",
    "interlace", "gamma", "srgb", "chromaticity",
}

_PNG_EXTS = (".png",)
_EXIF_EXTS = (".jpg", ".jpeg", ".webp", ".tiff", ".tif")


def _is_leak(text: str) -> bool:
    t = str(text).lower()
    return any(leak in t for leak in LEAK_KEYS)


def _is_structural(key: str, source: str) -> bool:
    return source == "info" and str(key).lower() in STRUCTURAL_KEYS


def scan_metadata(path: str) -> Dict[str, Any]:
    """
    Report every piece of embedded metadata found in an image, flagging which entries
    look like AI-generator leaks. Read-only -- never modifies the file.
    """
    ext = os.path.splitext(path)[1].lower()
    found: List[Dict[str, Any]] = []

    with Image.open(path) as img:
        for k, v in img.info.items():
            if k == "exif":
                continue  # raw bytes; handled via getexif() below instead
            sval = str(v)
            source = "png_text" if ext in _PNG_EXTS else "info"
            found.append({
                "key": str(k),
                "value": sval[:300] + ("…" if len(sval) > 300 else ""),
                "source": source,
                "leak": _is_leak(k) or _is_leak(sval[:120]),
                "structural": _is_structural(k, source),
            })

        try:
            exif = img.getexif()
            if len(exif) > 0:
                from PIL.ExifTags import TAGS
                for tag_id, value in exif.items():
                    tag = TAGS.get(tag_id, str(tag_id))
                    sval = str(value)
                    found.append({
                        "key": str(tag),
                        "value": sval[:300] + ("…" if len(sval) > 300 else ""),
                        "source": "exif",
                        "leak": _is_leak(tag) or _is_leak(sval[:120]),
                        "structural": False,
                    })
        except Exception:
            pass

    leaks = [f for f in found if f["leak"]]
    meaningful = [f for f in found if not f["structural"]]
    return {
        "asset": path,
        "entries_found": len(found),
        "entries": found,
        "leak_count": len(leaks),
        "leaks": leaks,
        "meaningful_count": len(meaningful),
        "clean": len(meaningful) == 0,
        "attribution": ATTRIBUTION,
    }


def clean_metadata(in_path: str, out_path: str, attribute: bool = False) -> Dict[str, Any]:
    """
    Strip all embedded metadata via a clean re-encode. If attribute=True, replace it
    with a single honest, visible tag instead of leaving the file silently blank.

    Returns a before/after report: what was found, what was removed, whether the
    output is now fully clean.
    """
    before = scan_metadata(in_path)
    ext = os.path.splitext(out_path)[1].lower()

    with Image.open(in_path) as img:
        img = img.copy()
        # Pillow's JPEG encoder falls back to img.info["comment"] even when `comment=`
        # isn't passed explicitly to save() -- unlike EXIF/pnginfo, which truly require
        # an explicit kwarg. Clear .info on the copy so no legacy field can leak through
        # a fallback path we didn't intend to use.
        img.info = {}
        save_kwargs: Dict[str, Any] = {}

        if ext in _PNG_EXTS and attribute:
            from PIL import PngImagePlugin
            pnginfo = PngImagePlugin.PngInfo()
            pnginfo.add_text("Software", ATTRIBUTION)
            save_kwargs["pnginfo"] = pnginfo
        if ext in _EXIF_EXTS and attribute:
            import piexif
            zeroth = {piexif.ImageIFD.Software: ATTRIBUTION.encode("utf-8")}
            save_kwargs["exif"] = piexif.dump(
                {"0th": zeroth, "Exif": {}, "GPS": {}, "1st": {}, "thumbnail": None}
            )

        img.save(out_path, **save_kwargs)

    after = scan_metadata(out_path)
    after_keys = {a["key"] for a in after["entries"]}
    removed = [e for e in before["entries"] if e["key"] not in after_keys]
    # Structural codec fields (jfif/dpi/gamma/...) are regenerated by any encoder and
    # were never "metadata" that could leak generator/personal info -- don't let their
    # mere presence flip fully_clean to False. Only meaningful (non-structural) entries
    # count, and attribute=True intentionally leaves exactly one (the Software tag).
    expected_after_count = 1 if attribute else 0

    return {
        "input": in_path,
        "output": out_path,
        "before_entries": before["entries_found"],
        "before_leaks": before["leak_count"],
        "before_leak_list": [e["key"] for e in before["leaks"]],
        "after_entries": after["entries_found"],
        "after_meaningful": after["meaningful_count"],
        "after_leaks": after["leak_count"],
        "removed": removed,
        "attributed": attribute,
        "fully_clean": after["meaningful_count"] <= expected_after_count,
        "attribution": ATTRIBUTION,
    }
